"""Security utilities: password hashing, verification, JWT tokens, and safe secrets."""

import logging
import secrets
from datetime import UTC, datetime, timedelta
from typing import Any, cast

from backend.core.config import settings
from jose import JWTError, jwt
from passlib.context import CryptContext
from passlib.exc import UnknownHashError

logger = logging.getLogger(__name__)

# Argon2id password hashing context (OWASP recommended) plus scrypt for legacy
# hashes that were migrated from the previous Flask backend.
pwd_context = CryptContext(
    schemes=["argon2", "scrypt"],
    deprecated="auto",
    argon2__time_cost=settings.ARGON2_TIME_COST,
    argon2__memory_cost=settings.ARGON2_MEMORY_COST,
    argon2__parallelism=settings.ARGON2_PARALLELISM,
    argon2__hash_len=32,
    argon2__salt_len=16,
)


def hash_password(password: str) -> str:
    """Hash a plaintext password with Argon2id."""
    return cast(str, pwd_context.hash(password))


def verify_password(password: str, hashed: str) -> bool:
    """Verify a plaintext password against a stored hash.

    Supports Argon2id hashes generated by this module and legacy Werkzeug
    scrypt hashes (``scrypt:...``) stored in the original database.

    A stored value that is not a recognisable hash (for example a credential
    seeded in plaintext) is treated as a failed verification rather than an
    error, so callers return 401 instead of surfacing a 500.
    """
    if not hashed:
        return False
    try:
        if hashed.startswith("scrypt:"):
            from werkzeug.security import check_password_hash

            return cast(bool, check_password_hash(hashed, password))
        return cast(bool, pwd_context.verify(password, hashed))
    except (UnknownHashError, ValueError):
        logger.warning("Rejected a login against a credential with an unrecognised hash format")
        return False


def needs_rehash(hashed: str) -> bool:
    """Return True if a stored hash should be upgraded to current Argon2id parameters."""
    if not hashed or hashed.startswith("scrypt:"):
        return True
    try:
        return cast(bool, pwd_context.needs_update(hashed))
    except (UnknownHashError, ValueError):
        return True


def generate_secure_token(nbytes: int = 32) -> str:
    """Generate a URL-safe random token."""
    return secrets.token_urlsafe(nbytes)


def generate_confirmation_token() -> str:
    """Generate an email confirmation token."""
    return secrets.token_urlsafe(32)


def create_access_token(
    data: dict[str, Any],
    expires_delta: timedelta | None = None,
) -> str:
    """Create a JWT access token.

    The token embeds the provided claims and an ``exp`` claim. By default it
    expires after ``settings.ACCESS_TOKEN_EXPIRE_MINUTES``.
    """
    to_encode = data.copy()
    if expires_delta:
        expire = datetime.now(UTC) + expires_delta
    else:
        expire = datetime.now(UTC) + timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)
    to_encode.update({"exp": expire, "type": "access"})
    return cast(str, jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM))


def create_member_access_token(
    data: dict[str, Any],
    expires_delta: timedelta | None = None,
) -> str:
    """Create a JWT access token scoped to a PulseMember."""
    to_encode = data.copy()
    if expires_delta:
        expire = datetime.now(UTC) + expires_delta
    else:
        expire = datetime.now(UTC) + timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)
    to_encode.update({"exp": expire, "type": "member_access"})
    return cast(str, jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM))


def create_refresh_token(
    data: dict[str, Any],
    expires_delta: timedelta | None = None,
) -> str:
    """Create a JWT refresh token with a longer lifetime."""
    to_encode = data.copy()
    if expires_delta:
        expire = datetime.now(UTC) + expires_delta
    else:
        expire = datetime.now(UTC) + timedelta(minutes=settings.REFRESH_TOKEN_EXPIRE_MINUTES)
    to_encode.update({"exp": expire, "type": "refresh"})
    return cast(str, jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM))


def create_member_refresh_token(
    data: dict[str, Any],
    expires_delta: timedelta | None = None,
) -> str:
    """Create a JWT refresh token scoped to a PulseMember."""
    to_encode = data.copy()
    if expires_delta:
        expire = datetime.now(UTC) + expires_delta
    else:
        expire = datetime.now(UTC) + timedelta(minutes=settings.REFRESH_TOKEN_EXPIRE_MINUTES)
    to_encode.update({"exp": expire, "type": "member_refresh"})
    return cast(str, jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM))


def decode_token(token: str) -> dict[str, Any]:
    """Decode and validate a JWT token, returning its payload."""
    return cast(dict[str, Any], jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM]))


def token_payload(token: str) -> dict[str, Any] | None:
    """Decode a JWT token without raising on error; returns None if invalid."""
    try:
        return decode_token(token)
    except JWTError:
        return None
