"""add deal room marketplace posts

Creates the three tables behind the Deal Room opportunity board: the posts
themselves, the expressions of interest against them, and the moderation
reports.

Hand-trimmed from the autogenerated diff. ``--autogenerate`` additionally
proposed dropping nine indexes on Education/Experiences/FundingRounds/
IncubatorFounders/Investements/StartupFounders/StartupIncubators and the
``uq_deal_room_startup`` unique constraint on ``deal_rooms``. Those reflect
pre-existing drift between the models and the live schema, not anything this
change introduces, and dropping a live uniqueness guarantee as a side effect of
adding a feature would be a silent data-integrity regression. They are
deliberately excluded and left for a dedicated reconciliation migration.

Revision ID: 2e8937d4b5e3
Revises: c5f2a81d3e90
Create Date: 2026-08-27 09:14:52.473678
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e8937d4b5e3"
down_revision: str | Sequence[str] | None = "c5f2a81d3e90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the marketplace tables."""
    op.create_table(
        "deal_room_posts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("author_member_id", sa.Integer(), nullable=False),
        sa.Column("post_type", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("summary", sa.String(length=400), nullable=False),
        sa.Column("details", sa.Text(), nullable=False),
        sa.Column("looking_for", sa.Text(), nullable=True),
        sa.Column(
            "counterparty_type",
            sa.String(length=40),
            nullable=False,
            server_default="any",
        ),
        sa.Column("sector", sa.String(length=120), nullable=True),
        sa.Column("stage", sa.String(length=60), nullable=True),
        sa.Column("location", sa.String(length=120), nullable=True),
        sa.Column("amount_min", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("amount_max", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("equity_offered", sa.String(length=60), nullable=True),
        sa.Column("commitment", sa.String(length=40), nullable=True),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column("tags", sa.String(length=400), nullable=True),
        sa.Column("entity_type", sa.String(length=20), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("entity_name", sa.String(length=200), nullable=True),
        sa.Column("deal_room_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="draft"),
        sa.Column(
            "moderation_status",
            sa.String(length=20),
            nullable=False,
            server_default="visible",
        ),
        sa.Column("moderation_note", sa.Text(), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("response_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["author_member_id"], ["pulse_members.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["deal_room_id"], ["deal_rooms.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_deal_room_posts_board",
        "deal_room_posts",
        ["status", "moderation_status", "published_at"],
    )
    op.create_index(
        "ix_deal_room_posts_author_status",
        "deal_room_posts",
        ["author_member_id", "status"],
    )
    op.create_index(
        "ix_deal_room_posts_type_status", "deal_room_posts", ["post_type", "status"]
    )
    op.create_index(
        op.f("ix_deal_room_posts_author_member_id"), "deal_room_posts", ["author_member_id"]
    )
    op.create_index(op.f("ix_deal_room_posts_post_type"), "deal_room_posts", ["post_type"])
    op.create_index(op.f("ix_deal_room_posts_sector"), "deal_room_posts", ["sector"])
    op.create_index(op.f("ix_deal_room_posts_stage"), "deal_room_posts", ["stage"])
    op.create_index(op.f("ix_deal_room_posts_location"), "deal_room_posts", ["location"])
    op.create_index(op.f("ix_deal_room_posts_status"), "deal_room_posts", ["status"])
    op.create_index(
        op.f("ix_deal_room_posts_moderation_status"), "deal_room_posts", ["moderation_status"]
    )
    op.create_index(
        op.f("ix_deal_room_posts_deal_room_id"), "deal_room_posts", ["deal_room_id"]
    )

    op.create_table(
        "deal_room_post_responses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("responder_member_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="pending"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["post_id"], ["deal_room_posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["responder_member_id"], ["pulse_members.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        # One response per member per post: the board offers "contact", not a
        # channel to message the same author repeatedly.
        sa.UniqueConstraint("post_id", "responder_member_id", name="uq_post_response_once"),
    )
    op.create_index(
        "ix_post_responses_post_created", "deal_room_post_responses", ["post_id", "created_at"]
    )
    op.create_index(
        op.f("ix_deal_room_post_responses_post_id"), "deal_room_post_responses", ["post_id"]
    )
    op.create_index(
        op.f("ix_deal_room_post_responses_responder_member_id"),
        "deal_room_post_responses",
        ["responder_member_id"],
    )
    op.create_index(
        op.f("ix_deal_room_post_responses_status"), "deal_room_post_responses", ["status"]
    )

    op.create_table(
        "deal_room_post_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("reporter_member_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=40), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="open"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("reviewed_by_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["post_id"], ["deal_room_posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["reporter_member_id"], ["pulse_members.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["reviewed_by_user_id"], ["User.UserId"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("post_id", "reporter_member_id", name="uq_post_report_once"),
    )
    op.create_index(
        op.f("ix_deal_room_post_reports_post_id"), "deal_room_post_reports", ["post_id"]
    )
    op.create_index(
        op.f("ix_deal_room_post_reports_reporter_member_id"),
        "deal_room_post_reports",
        ["reporter_member_id"],
    )
    op.create_index(
        op.f("ix_deal_room_post_reports_status"), "deal_room_post_reports", ["status"]
    )


def downgrade() -> None:
    """Drop the marketplace tables. Children first, so the FKs unwind cleanly."""
    op.drop_table("deal_room_post_reports")
    op.drop_table("deal_room_post_responses")
    op.drop_table("deal_room_posts")
